config/routes.rb
Infiniti::Application.routes.draw do
  root :to => 'pages#home'

  resources :pages do
    collection do
      post :send_contact_email
      post :send_newsletter_email
    end
  end

  match "home", to: "pages#home", as: :home
  match "about", to: "pages#about", as: :about
  match "contact", to: "pages#contact", as: :contact
  match "portfolio", to: "pages#portfolio", as: :portfolio
  match "products", to: "pages#products", as: :products
  match "privacy_policy", to: "pages#privacy", as: :privacy
  match "sitemap", to: "pages#sitemap", as: :sitemap
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def portfolio
  end

  def products
  end

  def privacy
  end

  def sitemap
  end

  # Email related actions
  def send_contact_email
    UserMailer.send_contact_email(params[:name], params[:email],
        params[:subject], params[:message]).deliver
    head :ok
  end

  def send_newsletter_email
    UserMailer.send_contact_email(params[:email]).deliver
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
      %title
        Infiniti Linens | #{content_for :page_title}
      = favicon_link_tag 'favicon.png'
      = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Dynalight'
      = stylesheet_link_tag 'application'
      = javascript_include_tag 'application'
    = csrf_meta_tag
%body
  .maindivcontainer
    = render partial: 'shared/header'
    = yield
    #backtotop.pagenav back to top
  = render partial: 'shared/footer'
  = render partial: 'shared/overlays'
  = render partial: 'shared/analytics'

app/views/pages/_big_carousel.html.haml
#sliderinfiniti
  #slidingFeatures
    %div{title: "Infiniti Linens#1"}
      %img{alt: "Infiniti Linens#1", src: "../assets/sliderimages/slide_image1.png"}/
    %div{title: "Infiniti Linens#2"}
      %img{alt: "Infiniti Linens#2", src: "../assets/sliderimages/slide_image2.png"}/
    %div{title: "Infiniti Linens#3"}
      %img{alt: "Infiniti Linens#3", src: "../assets/sliderimages/slide_image3.png"}/
    %div{title: "Infiniti Linens#4"}
      %img{alt: "Infiniti Linens#4", src: "../assets/sliderimages/slide_image4.png"}/

app/views/pages/_home_clients.html.haml
#sep
#testimonials_client
  .left_tc
    #clients
      %img{src: "../assets/clients/1.png"}/
      %img{src: "../assets/clients/2.png"}/
      %img{src: "../assets/clients/13.png"}/
      %img{src: "../assets/clients/11.png"}/
      %img{src: "../assets/clients/5.png"}/
      %img{src: "../assets/clients/10.png"}/
      %img{src: "../assets/clients/4.png"}/
      %img{src: "../assets/clients/8.png"}/
      %img{src: "../assets/clients/9.png"}/
      %img{src: "../assets/clients/6.png"}/
      %img{src: "../assets/clients/7.png"}/
      %img{src: "../assets/clients/12.png"}/
      %img{src: "../assets/clients/3.png"}/

app/views/pages/_home_three_box.html.haml
.boxes_3col
  .box1_3col
    .box_body
      .box_top
      .contents
        %h1
          Factory Direct with Retail like experience
        .picture
          %img{alt: "", src: "../assets/box_image1.png"}/
        %p
          Being a manufacturer, Infiniti Linens holds one of the largest stocks of Spun Polyester
          fabrics for Table Linen. Customers can order minimum quantities in custom dimensions
          from shades of 30 colors and whites.
      %a#cshade.link{href: "#inlinecolor"}
        %span.icon.cufon>
        Shade
        Card
      .clear
      .box_down
  .box2_3col
    .box_body
      .box_top
      .contents
        %h1
          Assorted Damask Range
        .picture
          %img{alt: "", src: "../assets/box_image2.png"}/
        %p
          We carry one of the widest range of Damask Napkins and Table Cloth fabrics in India.
          Table cloths can be custom ordered in square, circle and rectangle dimensions from
          30 inches to 120 inches without any joints and above 120 inches with joints.
      %a#designc.link{href: "#designbook"}
        %span.icon.cufon>
        Design
        Collection
      .clear
      .box_down
  .box3_3col
    .box_body
      .box_top
      .contents
        %h1
          Exclusive Jacquards
        .picture
          %img{alt: "", src: "../assets/box_image3.png"}/
        %p
          Our D’zire range enables Hotels/Restaurants to customize logos, brand names and
          designs on Linens in repeatless patterns, thereby giving a personalized touch in
          front of their esteemed clientele.
      %a#cgrill.link{href: "#inlinec"}
        %span.icon.cufon>
        Customizations
      .clear
      .box_down
  .clear

app/views/pages/about.html.haml
- content_for :page_title, 'About'

= render 'pages/big_carousel'
.slide_footer
  %h3{style: "font-family: 'Dynalight', cursive; font-size: 31px; color: #2b96f1; margin-top: 24px;\r\n                    position: relative;"} About Us
  %h2#slfoot
    Find out how and where it all began and where we are headed tomorrow. Our goal is the become the quintessential source of Hospitality Linens across the globe.
%br
%br

.box_full.subpage
  .rightcolumn
    .box_body
      .box_top
      .contents
        .r_column
          %h2
            Main menu
          .subnav
            .subnav_top
            %ul
              %li.page_item
                = link_to "Home", home_path
              %li.current_page_item
                = link_to "About", about_path
              %li.page_item
                = link_to "Contact", contact_path
              %li.page_item
                = link_to "Portfolio", portfolio_path
            %p
              Please click below to view/save our E-Brochure
              %br/
              %br/
              %a{href: "#", onclick: "window.open('http://www.infinitilinens.com/Infiniti Linens-E-brochure.pdf', 'NewWin');", style: "color: #0098d1; font-size: 12px; text-decoration: underline"}
                E-Brochure Link
            .subnav_down
          .box
        .page
          .page_border.gallery
            %p
              %strong Our Establishment
              %br/
              Incorporated in 1987, Kalpesh Synthetics Pvt Ltd has been catering to domestic and
              international Textile market demands for the last 23 years.
              %br/
              %br/
              %strong Where it all began
              %br/
              Our forefathers first began trading bath towels and table linens in 1965. Later
              on when next generations of family entered the business and studied existing textile
              market conditions, they soon recognized a lack of quality textile manufacturers
              in the domestic market. This led to construction of Kalpesh Synthetics’s first textile
              manufacturing facility in 1988.
              %br/
              %br/
              %strong What are we doing
              %br/
              Since then Kalpesh Synthetics Pvt Ltd has been synonymous with quality and excellence
              in the industry.
            %ul
              %li
                After successfully catering to the demands of domestic markets for over a decade
                we expanded our focus to international markets.
              %li
                We are now a leading manufacturing and distribution company with a strong focus
                on supply of high quality and competitively priced Hospitality Linens.
              %li
                Our experience, market knowledge and product diversity along with continued investment
                in latest machinery ensures that we can meet any type of customer requirements.
              %li
                In the next few years, our goal is to expand our products and services to the extent
                where we are known as the quintessential source for Hospitality Linens across the
                globe, be it a stand alone restaurant or multinational group of Hotel chains.
            We now have our corporate head quarters in Mumbai with our state of the art manufacturing
            facilities and distribution centers located in textile zones of Gujarat.
        .clear
      .clear
      .box_down

app/views/pages/contact.html.haml
- content_for :page_title, 'Contact Us'

= render 'pages/big_carousel'
.slide_footer
  %h3{style: "font-family: 'Dynalight', cursive; font-size: 31px; color: #2b96f1; margin-top: 24px;\r\n                    position: relative;"}
    Contact Us
  %h2#slfoot
    If you have any suggestions for us, then we would love to hear your feedback as
    this would help us grow and make better and improved products as per your needs
    and desires.
%br
%br

.box_full.subpage
  .rightcolumn
    .box_body
      .box_top
      .contents
        .r_column
          %h2
            Main menu
          .subnav
            .subnav_top
            %ul
              %li.page_item
                = link_to "Home", home_path
              %li.page_item
                = link_to "About", about_path
              %li.current_page_item
                = link_to "Contact", contact_path
              %li.page_item
                = link_to "Portfolio", portfolio_path
            %p
              Please click below to view/save our E-Brochure
              %br/
              %br/
              %a{href: "#", onclick: "window.open('http://www.infinitilinens.com/Infiniti Linens-E-brochure.pdf', 'NewWin');", style: "color: #0098d1; font-size: 12px; text-decoration: underline"}
                E-Brochure Link
            .subnav_down
          .box
        .page
          .page_border.gallery
            .entry
              #SocialBox
                .hoffice
                  %h4 Head Office:
                  3, Kuntal, Modi Industrial Estate,
                  %br
                  L.B.S. Marg, Ghatkopar (West)
                  %br/
                  Mumbai – 400086 India
                  %br/
                  %strong Phone
                  +91 8080036412/ 13/ 14
                  %br/
                  %strong Fax
                  +91 22 25094787
                  %br/
                .foffice
                  %h4
                    Factory:
                  Kalpesh Synthetics Pvt Ltd.
                  %br/
                  Dehri Road, Umergaon, Dist Valsad,
                  %br/
                  Gujarat – 396171 India
                  %br/
                .sociallinks
                  %h4
                    Infiniti @ Email:
                  %a{href: "mailto:info@infinitilinens.com"} info@infinitilinens.com
                  %br/
                  %br/
                  %h4
                    Infiniti @ Social:
                    %a{href: "https://twitter.com/infinitilinens"}
                      %img{alt: "il", src: "../assets/social/infiniti_twitter.png"}/
                    %a{href: "http://www.facebook.com/pages/FB-Linen-Infiniti-Linens/308724029168969"}
                      %img{alt: "il", src: "../assets/social/infiniti_facebook.png"}/
                    %img{alt: "il", src: "../assets/social/infiniti_linkedin.png"}/
                %br{style: "clear: left;"}/
              %div{style: "margin: auto; width: 25%; font-family: 'Dynalight', cursive; font-size: 26px;\r\n                                        color: #2b96f1"}
                \--- Write to us ---
              .messagewrapper
                = form_for :email, url: send_contact_email_pages_path, remote: true, method: :post, html: { class: 'commentForm' } do |f|
                  %span#notifications
                  .lcontact
                    %ol.clearfix
                      %li
                        %label{for: "firstname"}
                          Name
                        %input#contactName{name: "firstname", size: "35", type: "text"}/
                      %br/
                      %li
                        %label{for: "email"}
                          E-Mail
                        %input#contactEmail{name: "email", size: "35", type: "text"}/
                      %li
                        %label{for: "subject"}
                          Subject
                        %input#contactSubject{name: "subject", size: "35", type: "text"}/
                  .rcontact
                    %ol
                      %li
                        %label{for: "content"}
                          Message
                        %textarea#contactMessage{cols: "32", name: "content", rows: "7"}
                      %li.last
                        %input#msubmit{name: "submit", type: "submit", value: "Submit"}/
                  %div{style: "clear: both;"}
                %br/
        .clear
      .clear
      .box_down

app/views/pages/home.html.haml
- content_for :page_title, 'Home'

= render 'pages/big_carousel'
.slide_footer
  %h3{style: "font-family: 'Dynalight', cursive; font-size: 31px; color: #2b96f1; margin-top: 24px;\r\n                    position: relative;"} Welcome
  %h2#slfoot
    %b{style: "color: #005180;"} Infiniti Linens
    is a manufacturer of a wide variety
    of Linens for worldwide Hospitality industry. Abundant research and technology have
    gone into making a superlative product range which continues to set new standards
    in the industry. Our linens come highly rated for their performance, consistency,
    value and durability. Product range comprises of Table and Bath linens in an assortment
    of blends, styles and colours.
%br
%br
= render 'pages/home_three_box'
= render 'pages/home_clients'

app/views/pages/portfolio.html.haml
- content_for :page_title, 'Portfolio'

= render 'pages/big_carousel'
.slide_footer
  %h3{style: "font-family: 'Dynalight', cursive; font-size: 31px; color: #2b96f1; margin-top: 24px; position: relative;"}
    Portfolio
  %h2#slfoot
    %b{style: "color: #005180;"} Infiniti Linens
    is a manufacturer
    of a wide variety of Linens for worldwide Hospitality industry. Abundant research
    and technology have gone into making a superlative product range which continues
    to set new standards in the industry. Our linens come highly rated for their performance,
    consistency, value and durability. Product range comprises of Table and Bath linens
    in an assortment of blends, styles and colors.
%br
%br

.box_full.subpage
  .rightcolumn
    .box_body
      .contents
        .r_column
          %h2
            Main menu
          .subnav
            .subnav_top
            %ul
              %li.page_item
                = link_to "Home", home_path
              %li.page_item
                = link_to "About", about_path
              %li.page_item
                = link_to "Contact", contact_path
              %li.current_page_item
                = link_to "Portfolio", portfolio_path
            %p
              Please click below to view/save our E-Brochure
              %br/
              %br/
              %a{href: "#", onclick: "window.open('http://www.infinitilinens.com/Infiniti Linens-E-brochure.pdf', 'NewWin');", style: "color:#0098d1;font-size:12px;text-decoration:underline"} E-Brochure Link
            .subnav_down
          .box
        .page
          .page_border
            %br/
            %img.alignleft{alt: "Hotels & Restaurants", src: "../assets/portfolio/foodandbeverages.png"}/
            %h4.portfoliotitle
              Table Linen
            %p
              Product range comprises of Dinner and Cocktail Table Napkins, Table Cloths, Aprons,
              Chair Covers, Placemats and Traymats in an assortment of styles, designs and colors
              in Spun Polyester, Cotton and Cotton rich Polyester blends
              %br/
              = link_to 'Learn More', products_path
            .clear
            %br/
        .clear
      .clear

app/views/pages/privacy.html.haml
- content_for :page_title, 'Privacy Policy'

#otherpp
  %h3
    Privacy Policy
  %strong General Information
  %br/
  %p
    We collect the e-mail addresses of those who communicate with us via e-mail and
    those who have registered with us for our newsletters. The is used to improve the
    quality of our products and make our customer aware about the new and enhanced services
    we can offer them with time.

app/views/pages/products.html.haml
- content_for :page_title, 'Products'

.mp_wrapper
  #mp_content_wrapper.mp_content_wrapper
    .mp_content
      %img{alt: "img", src: "../assets/products/main/tablelinen1.png"}/
  .mp_player
    .triangle-border.detailed
      %strong.headertable Table Linens
      %hr/
      %span.detailedp Select from the products.
    .colorsize
      %a#qualitychart.csbuttons{href: "#inline2"} Quality Chart
      %em /
      %a#colorshade.csbuttons{href: "#inline1"} Color Chart
    .rowbar
      .rows
        .left
          %img{src: "../assets/products/thumbs/plains_thumb.png"}/
        .right
          Basics
          %br/
          %em Traditional designs
        %div{style: "clear: both"}
      .rows
        .left
          %img{src: "../assets/products/thumbs/classics_thumb.png"}/
        .right
          Classics
          %br/
          %em Timeless designs
        %div{style: "clear: both"}
      .rows
        .left
          %img{src: "../assets/products/thumbs/jacquard_thumb.png"}/
        .right
          Jacquards
          %br/
          %em Engineered concepts
        %div{style: "clear: both"}
      .rows
        .left
          %img{src: "../assets/products/thumbs/dzire_thumb.png"}/
        .right
          D'zire
          %br/
          %em Dream collection
        %div{style: "clear: both"}
  %ul#mp_albums.mp_albums.jcarousel-skin
    %li#napkins
      %img{src: "../assets/products/thumbs/plains_poly.png"}/
      %h4.subtitle
        Napkins
    %li#tablecloths
      %img{src: "../assets/products/thumbs/tablecloth_thumb.png"}/
      %h4.subtitle
        Table Cloths
    %li#trunners
      %img{src: "../assets/products/thumbs/tablerunner_thumb.png"}/
      %h4.subtitle
        Table Runners
    %li#aprons
      %img{src: "../assets/products/thumbs/aprons_thumb.png"}/
      %h4.subtitle
        Aprons
    %li#handtowels
      %img{src: "../assets/products/thumbs/handtowels_thumb.png"}/
      %h4.subtitle
        Hand Towels
  %div{style: "display: none;"}
    #inline1{style: "width: 700px; height: 500px; overflow: auto;"}
      %h2
        Color Shade
      %hr/
      %img{src: "../../assets/colorbook.png"}/
    #inline2{style: "width: 480px; height: 500px; overflow: auto;"}
      %h2
        Table Linen - Quality Guide
      %div
        %strong Polyester
        %div
          Fabrics are made from 2 ply Spun Polyester yarns having the best linting, picking
          pilling resistant properties. Their innovative soil release and water absorbing
          qualities enable the fabric to retain colours and size after multiple washings.
          A longer shelf life with significantly fewer stain rejects gives the fabric a soft
          feel good look day after day.
      %hr{style: "width: 80%; align: center; color: #2B96F1"}/
      %div
        %strong Cotton
        %div
          Fabrics are made from 2 ply Cotton Ringspun Combed yarns. Ringspun technique gives
          a distinctive softness to the fabric and enhances suppleness and smoothness of the
          table linen.
      %hr{style: "width: 80%; align: center; color: #2B96F1"}/
      %div
        %strong Cotton-Polyester
        %div
          Fabrics are made from a versatile cotton rich polyester blend which retains the
          coolness and lightness of cotton fiber and also adds strength, durability and wrinkle
          resistance of polyester. This uniqueness guarantees longer life and better colour
          lasting than a regular cotton fabric table linen.
      .basiclogo
        %img{src: "../assets/logosmall.png"}/
  .backgroundeffect
%br
%br

app/views/pages/sitemap.html.haml
- content_for :page_title, 'Sitemap'

#otherpp
  %h3
    Sitemap
  %ul
    %li
      = link_to 'Infiniti Linens: Home', home_path
    %li
      = link_to 'Infiniti Linens: Portfolio', portfolio_path
    %li
      = link_to 'Infiniti Linens: About', about_path
    %li
      = link_to 'Infiniti Linens: Product Gallery', products_path
      %ul
        %li
          = link_to 'Napkin', products_path + '?napkins'
        %li
          = link_to 'Table Cloths', products_path + '?tablecloths'
        %li
          = link_to 'Table Runners', products_path + '?trunners'
        %li
          = link_to 'Aprons', products_path + '?aprons'
    %li
      = link_to 'Infiniti Linens: Contact', contact_path
  #misclinks
    %em Other Important Links
    %ul
      %li
        %a#qualitychart{href: "#inline2"} Quality Chart
      %li
        %a#colorshade{href: "#inline1"} Color Chart
      %li
        %a{href: "#", onclick: "window.open('http://www.infinitilinens.com/Infiniti Linens-E-brochure.pdf', 'NewWin');"}
          E-Brochure Link
= render 'shared/color_quality_overlays'

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28432813-1']);
  _gaq.push(['_trackPageview']);

  (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_color_quality_overlays.html.haml
%div{style: "display: none;"}
  #inline1{style: "width: 700px; height: 500px; overflow: auto;"}
    %h2
      Color Shade
    %hr/
    %img{src: "../assets/colorbook.png"}/
  #inline2{style: "width: 480px; height: 500px; overflow: auto;"}
    %h2
      Table Linen - Quality Guide
    %div
      %strong Polyester
      %div
        Fabrics are made from 2 ply Spun Polyester yarns having the best linting, picking
        pilling resistant properties. Their innovative soil release and water absorbing
        qualities enable the fabric to retain colours and size after multiple washings.
        A longer shelf life with significantly fewer stain rejects gives the fabric a soft
        feel good look day after day.
    %hr{style: "width: 80%; align: center; color: #2B96F1"}/
    %div
      %strong Cotton
      %div
        Fabrics are made from 2 ply Cotton Ringspun Combed yarns. Ringspun technique gives
        a distinctive softness to the fabric and enhances suppleness and smoothness of the
        table linen.
    %hr{style: "width: 80%; align: center; color: #2B96F1"}/
    %div
      %strong Cotton-Polyester
      %div
        Fabrics are made from a versatile cotton rich polyester blend which retains the
        coolness and lightness of cotton fiber and also adds strength, durability and wrinkle
        resistance of polyester. This uniqueness guarantees longer life and better colour
        lasting than a regular cotton fabric table linen.
    .basiclogo
      %img{src: "../assets/logosmall.png"}/

app/views/shared/_footer.html.haml
.footer
  %div{style: "width: 1090px; margin: auto;"}
    .plinks{style: "float: left; width: 22%; margin-left: 3%;"}
      %h2
        %img.iconsfoot{src: "../assets/icons/links_blue.png"}
        %span.iconsfoot_text Browse
      #menu2
        %ul
          %li
            = link_to 'Site Map', sitemap_path
          %li
            = link_to 'Privacy Policy', privacy_path

    %div{style: "float: left; width: 35%; margin-left: 4%;"}
      %h2
        %img.iconsfoot{src: "../assets/icons/newsletter_blue.png"}
        %span.iconsfoot_text Newsletter
        %br
        %span.notice
        = form_for :newsletter, url: send_newsletter_email_pages_path, remote: true, html: { class: 'send_newsletter'} do |f|
          %input.search{type: "text", name: 'email', placeholder: "info@infinitilinens.com", class: 'newsletterEmail'}
          %input.button{type: "submit", value: "Send"}
      %em
        You'll get an email about our website and product-related updates and we'll never
        share your email address.

    %div{style: "float: left; width: 27%; margin-left: 4%;"}
      %h2
        %img.iconsfoot{src: "../assets/icons/home_blue.png"}
        %span.iconsfoot_text Contact Us
      %p
        Infiniti Linens, 3, Kuntal, Modi Industrial Estate,
        %br
        L.B.S. Marg, Ghatkopar (W) Mumbai – 400086 India
        %br
        %b Tel:
        +91 8080036412/ 13/ 14
        %br
    %br{style: "clear: left;"}

  .foot_footer
    %div{style: "width: 36%; padding-top: 2px; position: relative; float: left; margin-left: 11%"}
      © Copyrights 2014. All Rights Reserved. Kalpesh Synthetics Pvt. Ltd.
    %div{style: "padding-top: 2px; margin-left: 75%"}
      %span
        Design|Code --
        %a{href: "http://sinhaabhijitp.tumblr.com/", target: "_blank"} PositiveVibes
    %div{style: "clear: both"}

app/views/shared/_header.html.haml
.header
  .logo
    %a{href: "/", title: "Home"}
      %span.logo
  #followinfiniti
    %a{href: TWITTER_URL}
      %img{alt: "infiniti-twitter", src: "../assets/social/infiniti_twitter.png"}
    %a{href: FACEBOOK_URL}
      %img{alt: "infiniti-facebook", src: "../assets/social/infiniti_facebook.png"}
    %img{alt: "infiniti-linkedin-comingsoon", src: "../assets/social/infiniti_linkedin.png"}

.dcjq-mega-menu
  %ul#mega-menu-tut.menu
    %li
      = link_to "Home", home_path, class: 'mainmenu'
    %li
      = link_to "About", about_path
    %li
      = link_to portfolio_path do
        %span Products
      %ul
        %li#menu-item-1
          = link_to 'Table Linen', products_path
          %ul
            %li
              = link_to 'Napkin', products_path + '?napkins'
            %li
              = link_to 'Table Cloths', products_path + '?tablecloths'
            %li
              = link_to 'Table Runners', products_path + '?trunners'
            %li
              = link_to 'Aprons', products_path + '?aprons'
            %li
              = link_to 'Miscellaneous', products_path
    %li
      = link_to "Contact", contact_path

app/views/shared/_overlays.html.haml
%div{style: "display: none;"}
  #inlinec{style: "width: 600px; height: 500px; overflow: auto;"}
    %strong D'Zire Collections
    %hr
    %em Infiniti Linens
    %br
    %br
    %img{src: "../assets/products/backleaf.gif?rand=\#{SecureRandom.hex}"}
  #inlinecolor{style: "width: 700px; height: 500px; overflow: auto;"}
    %strong Color Chart
    %hr
    %em Infiniti Linens
    %br
    %img{src: "../assets/colorbook.png"}
    %p
      Note: Actual colors may vary due to individual computer screen interpretation.
  #designbook{style: "width: 700px; height: 500px; overflow: auto;"}
    %strong Design Collections
    %hr
    %em Infiniti Linens
    %br
    %img{src: "../assets/designimage.png"}